all: demo_1 demo_2 question2 question3 question4

demo_1:
	mpicc -Wall -Wextra -std=c99 demo_1.c -o demo_1 -lm
demo_2:
	mpicc -Wall -Wextra -std=c99 demo_2.c -o demo_2 -lm
question2: question2.c
	mpicc -Wall -Wextra -std=c99 question2.c -o question2 -lm
question3: question3.c
	mpicc -Wall -Wextra -std=c99 question3.c -o question3 -lm
question4: question4.c
	mpicc -Wall -Wextra -std=c99 question4.c -o question4 -lm

